FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install --no-audit --no-fund

FROM base AS dev
WORKDIR /app
CMD ["npm", "run", "dev:host"]

FROM base AS build
WORKDIR /app
COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
